precompile(Tuple{typeof(Base.create_expr_cache), String, String, Array{Base.Pair{Base.PkgId, UInt64}, 1}, Base.UUID})
precompile(Tuple{Type{NamedTuple{(:stderr,), T} where T<:Tuple}, Tuple{Base.TTY}})
precompile(Tuple{getfield(Base, Symbol("##pipeline#549")), Nothing, Nothing, Base.TTY, Bool, typeof(Base.pipeline), Base.Cmd})
precompile(Tuple{getfield(Base, Symbol("#pipeline##kw")), NamedTuple{(:stderr,), Tuple{Base.TTY}}, typeof(Base.pipeline), Base.Cmd})
precompile(Tuple{getfield(Base, Symbol("##open#559")), Bool, Bool, typeof(Base.open), Base.CmdRedirect, Base.TTY})
precompile(Tuple{typeof(Base.open), Base.CmdRedirect, String, Base.TTY})
precompile(Tuple{typeof(Base.convert), Type{IO}, Base.PipeEndpoint})
precompile(Tuple{typeof(Base.getproperty), Base.Process, Symbol})
precompile(Tuple{typeof(Base.show), Base.GenericIOBuffer{Array{UInt8, 1}}, Array{String, 1}})
precompile(Tuple{typeof(Base.write), Base.PipeEndpoint, String})
precompile(Tuple{typeof(Base.print), Base.GenericIOBuffer{Array{UInt8, 1}}, Base.UUID})
precompile(Tuple{getfield(Base, Symbol("##sprint#338")), Nothing, Int64, typeof(Base.sprint), Function, UInt64})
precompile(Tuple{typeof(Base.show), Base.GenericIOBuffer{Array{UInt8, 1}}, UInt64})
precompile(Tuple{typeof(Base.write), Base.Process, String})
precompile(Tuple{typeof(Base.show_delim_array), Base.GenericIOBuffer{Array{UInt8, 1}}, Tuple{UInt64, UInt64}, Char, Char, Char, Bool, Int64, Int64})
precompile(Tuple{typeof(Base.print), Base.GenericIOBuffer{Array{UInt8, 1}}, Tuple{UInt64, UInt64}})
precompile(Tuple{typeof(Base.display_error), Array{Any, 1}})
precompile(Tuple{typeof(Base.show_exception_stack), Base.IOContext{Base.TTY}, Array{Any, 1}})
precompile(Tuple{typeof(Base.display_error), Base.TTY, Array{Any, 1}})
precompile(Tuple{getfield(Base, Symbol("#printstyled##kw")), NamedTuple{(:bold, :color), Tuple{Bool, Symbol}}, typeof(Base.printstyled), Base.TTY, String})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{LoadError, Array{Base.StackTraces.StackFrame, 1}}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{LoadError, Array{Base.StackTraces.StackFrame, 1}}, Int64, Int64})
precompile(Tuple{getfield(Base, Symbol("##showerror#651")), Bool, typeof(Base.showerror), Base.IOContext{Base.TTY}, LoadError, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{getfield(Base, Symbol("#showerror##kw")), NamedTuple{(:backtrace,), Tuple{Bool}}, typeof(Base.showerror), Base.IOContext{Base.TTY}, LoadError, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{typeof(Base.show_reduced_backtrace), Base.IOContext{Base.TTY}, Array{Any, 1}, Bool})
precompile(Tuple{typeof(Base.show_backtrace), Base.IOContext{Base.TTY}, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{getfield(Base, Symbol("##showerror#648")), Bool, typeof(Base.showerror), Base.IOContext{Base.TTY}, ErrorException, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{getfield(Base, Symbol("#showerror##kw")), NamedTuple{(:backtrace,), Tuple{Bool}}, typeof(Base.showerror), Base.IOContext{Base.TTY}, ErrorException, Array{Base.StackTraces.StackFrame, 1}})
precompile(Tuple{getfield(Base, Symbol("##with_output_color#701")), Bool, typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}})
precompile(Tuple{typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}})
precompile(Tuple{getfield(Base, Symbol("#649#650")){ErrorException}, Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, String})
precompile(Tuple{typeof(Base.join), Base.IOContext{Base.TTY}, Array{String, 1}, String, String})
precompile(Tuple{typeof(Base.join), Base.IOContext{Base.TTY}, Array{Any, 1}, String, String})
precompile(Tuple{typeof(Base.show_method_params), Base.IOContext{Base.TTY}, Array{Any, 1}})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Module})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, Module})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, Module})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Method})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Core.MethodInstance})
precompile(Tuple{getfield(Base, Symbol("##show#383")), Symbol, typeof(Base.show), Base.IOContext{Base.TTY}, Core.CodeInfo})
precompile(Tuple{typeof(Base.StackTraces.show_spec_linfo), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame})
precompile(Tuple{getfield(Base.StackTraces, Symbol("##show#9")), Bool, typeof(Base.show), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame})
precompile(Tuple{getfield(Base, Symbol("##show_trace_entry#667")), String, typeof(Base.show_trace_entry), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame, Int64})
precompile(Tuple{getfield(Base, Symbol("#show_trace_entry##kw")), NamedTuple{(:prefix,), Tuple{String}}, typeof(Base.show_trace_entry), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame, Int64})
precompile(Tuple{typeof(Base.show_tuple_as_call), Base.IOContext{Base.TTY}, Symbol, Type, Bool, Nothing})
precompile(Tuple{typeof(Base.show_tuple_as_call), Base.IOContext{Base.TTY}, Symbol, Type, Bool})
precompile(Tuple{getfield(Base, Symbol("##with_output_color#701")), Bool, typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}, String})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, Type{T} where T})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, Type})
precompile(Tuple{typeof(Base.show_sym), Base.IOContext{Base.TTY}, String})
precompile(Tuple{getfield(Base, Symbol("##show_sym#372")), Bool, typeof(Base.show_sym), Base.IOContext{Base.TTY}, String})
precompile(Tuple{getfield(Base, Symbol("##show_sym#372")), Bool, typeof(Base.show_sym), Base.IOContext{Base.TTY}, Symbol})
precompile(Tuple{typeof(Base.show_type_name), Base.IOContext{Base.TTY}, Core.TypeName})
precompile(Tuple{typeof(Base.show_datatype), Base.IOContext{Base.TTY}, DataType})
precompile(Tuple{typeof(Base.show_delim_array), Base.IOContext{Base.TTY}, Array{Any, 1}, Char, Char, Char, Bool, Int64, Int64})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Type})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, Int64, Vararg{Any, N} where N})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, Int64})
