name = "julia_app"
uuid = "cdf55cd6-4611-4780-8d87-89a0cc42fa99"
authors = ["Zackary Windham <zwindham@byu.edu>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
